// Single source of truth — read version from package.json
const _pkg = require('../package.json') as { version: string };
export const VERSION: string = _pkg.version;
export { Agent } from './agent';
export { OpenAIProvider } from './providers/openai';
export { AnthropicProvider } from './providers/anthropic';
export { ToolRegistry } from './tools';
export { ContextManager } from './context/manager';
export { buildRepoMap } from './context/repo-map';
export { SessionManager } from './history';
export { MemoryManager } from './memory';
export { parseToolCalls, parseJsonModeResponse, buildToolCallSchema } from './parser';
export { classifyComplexity, classifyToolTier, selectModel, autoDetectTierModels } from './router';
export type { ModelTier, RouterConfig } from './router';
export { Orchestrator, generateTaskId } from './orchestrator';
export type { AgentTask, AgentResult, OrchestratorConfig } from './orchestrator';
export { DelegateTool } from './tools/delegate';
export { loadPlugins } from './plugins';
export { loadMCPTools } from './mcp';
export { MODEL_REGISTRY, PROVIDER_DEFAULTS, getModelInfo, detectProvider } from './providers/registry';
export type { ModelInfo } from './providers/registry';
export { CapabilityChecker } from './capabilities';
export type { ToolCapabilities, CapabilityConfig } from './capabilities';
export { deriveSessionKey, signMessage, verifyMessage, verifyMessages } from './integrity';
export type { IntegrityResult } from './integrity';
export { ReplayProvider, loadSessionForReplay, compareOutputs, listReplayableSessions } from './replay';
export type { SessionReplayData, ReplayDivergence } from './replay';
export { MetricsCollector } from './metrics';
export type { MetricsSnapshot, CounterValue, HistogramValue, Span, SpanEvent } from './metrics';
export { RiskScorer } from './risk';
export type { RiskAssessment, RiskFactor } from './risk';
export { exportSarif, sarifToString } from './sarif';
export type { SarifLog, SarifResult, SarifRule } from './sarif';
export { PolicyEnforcer, loadPolicy, generateDefaultPolicyFile } from './policy';
export type { Policy, PolicyRbac, PolicyRole } from './policy';
export { encrypt, decrypt, encryptLine, decryptLine, encryptContent, decryptContent, isEncryptionEnabled, deriveKey, getPassphrase } from './encryption';
export type { EncryptionConfig } from './encryption';
export { banner, randomGreeting, compactBanner, formatReaction, codiReact, sessionSummaryBanner, randomBanner, CODI_FACE, BANNER_1, BANNER_2, BANNER_3, animateReveal, animateVisorScan, animateEyeBoot, animateBootSequence, animateTyping, animateSessionEnd, animateWelcomeBoot, shouldAnimate } from './banner';
export type { CodiMood, CodiReaction, AnimationSpeed, AnimationWriter, AnimationOptions } from './banner';
export { box, riskBar, permissionCard, spinner, progressStep, diffPreview, sessionHeader, summaryBox, UI, BOX, providerCard, guidedPrompts } from './ui';
export type { ProviderCardItem } from './ui';
export { TokenTracker, estimateRunCost } from './telemetry';
export type { UsageRecord, SessionSummary, CostEstimate } from './telemetry';
export { BrowserSession } from './tools/browser';
export { runDoctor, formatDoctorReport } from './doctor';
export { autoDetect, pickBestLocalModel, runQuickSetup, RECOMMENDED_MODELS } from './setup';
export type { AutoDetectResult } from './setup';
export { DARK_THEME, LIGHT_THEME, MONO_THEME, loadTheme, setTheme, getTheme, applyColor, getThemeNames } from './theme';
export { ProviderRateLimiter, PROVIDER_RATE_DEFAULTS } from './provider-rate-limiter';
export { LayoutEngine } from './tui/layout';
export type { Panel, PanelPosition, LayoutConfig } from './tui/layout';
export { parseKeypress, keyToAction, createKeyboardListener } from './tui/keyboard';
export type { KeyEvent, TuiAction } from './tui/keyboard';
export { Screen } from './tui/screen';
export { TuiMode } from './tui/tui-mode';
export { DashboardServer } from './dashboard/server';
export type { RouteHandler } from './dashboard/server';
export { registerApiRoutes } from './dashboard/api';
export type { TuiStep, TuiConfig } from './tui/tui-mode';
export type { ProviderRateConfig } from './provider-rate-limiter';
export type { Theme } from './theme';
export type { HealthCheck, DoctorReport } from './doctor';
// v2.5.0 — App Connectors, Vault & Skills
export { VaultManager } from './vault';
export type { VaultCredential } from './vault';
export { ConnectorRegistry } from './connectors/registry';
export type { Connector, ConnectorAction } from './connectors/base';
export { GitHubConnector } from './connectors/github';
export { SlackConnector } from './connectors/slack';
export { JiraConnector } from './connectors/jira';
export { LinearConnector } from './connectors/linear';
export { AppConnectorTool } from './tools/app-connector';
export { GraphicsTool } from './tools/graphics';
export { OpenAIImagesConnector } from './connectors/openai-images';
export { ReplicateConnector } from './connectors/replicate';
export { loadSkills, skillToTool } from './skills';
export type { SkillDefinition, SkillStep } from './skills';
export * from './types';
